version: '3.8'

services:
  todo-app:
    build: .
    container_name: todo-txt-manager
    ports:
      - "5001:5000"
    volumes:
      # Mount a volume for persistent user data and todo files
      - todo_data:/app/data
    environment:
      - FLASK_ENV=production
      - FLASK_APP=app.py
      - TODO_FILES_DIR=/app/data
      - SECRET_KEY=${SECRET_KEY:-please-change-this-secret-key-in-production}
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/login"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  todo_data:
    driver: local
